version: 0.2

env:
  parameter-store:
    AWS_ACCESS_KEY_ID: /MyApp/AWSAccessKey
    AWS_SECRET_ACCESS_KEY: /MyApp/AWSSecretKey

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=566101360449.dkr.ecr.us-east-1.amazonaws.com/my-docker-repo
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)i
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - sed -i "s|<REPLACE_WITH_AWS_ACCESS_KEY>|$AWS_ACCESS_KEY_ID|" Dockerfile
      - sed -i "s|<REPLACE_WITH_AWS_SECRET_KEY>|$AWS_SECRET_ACCESS_KEY|" Dockerfile
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"nodeapp","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json 
artifacts:
    files: imagedefinitions.json
